apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-test-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: cuda-vector-add
        image: nvidia/cuda:11.0-base
        command: ["sh", "-c", "nvidia-smi && echo 'GPU test successful!'"]
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "1"
            memory: "2Gi"
            nvidia.com/gpu: 1
      restartPolicy: Never
  backoffLimit: 1
