apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.medium", "t3.large"]
  provider:
    subnetSelector:
      karpenter.sh/discovery: AURA-eks-dev
    securityGroupSelector:
      karpenter.sh/discovery: AURA-eks-dev
  ttlSecondsAfterEmpty: 60